name: Question 3 DS

on: [push]

permissions:
  contents: write

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Copie du fichier Q3.java dans Q3_archive_TOTO
        run: | 
          echo "Maël Vauthier" > Q3_archive_TOTO.txt
          cat Q3.java >> Q3_archive_TOTO.txt
          
      - name: Commit et push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Q3_archive_TOTO.txt
          git commit -m "Ajout de Q3_archive_TOTO.txt" || echo "Aucun changement à valider"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
